---
- name: Create MySQL directory
  file:
    path: /home/{{default_user}}/{{ CONTAINER_NAME }}/
    state: directory  

- name: MySQL Data Volume
  docker_volume:
    name: "{{ CONTAINER_NAME }}_data"
    state: "{{ VOLUME_STATE }}"

- name: MySQL config file
  template:
    src: my.cnf.j2
    dest: /home/{{default_user}}/{{ CONTAINER_NAME }}/my.cnf    

- name: MySQL
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: "{{ IMAGE }}:{{ BUILD }}"
    pull: "true"
    recreate: "yes"
    env:
      MYSQL_ROOT_PASSWORD: "{{ ROOT_PASSWORD }}"
      MYSQL_DATABASE: "{{NEW_DATABASE}}"
      MYSQL_USER: "{{NEW_USER}}"
      MYSQL_PASSWORD: "{{NEW_PASSWORD}}"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    restart_policy: "unless-stopped"
    published_ports:
      - "0.0.0.0:{{ PORT }}:{{ PORT }}"
    volumes:
      - /home/{{default_user}}/{{ CONTAINER_NAME }}/my.cnf:/etc/mysql/my.cnf
      - '{{ CONTAINER_NAME }}_data:/var/lib/mysql'